name: Code analysis checks
on:
  push:
    paths:
      - "*.js"
      - "*.json"
      - "*.yaml"
      - "packages/**"
      - ".github/workflows/code.yml"

env:
  NODE_VERSION: 20.x

jobs:
  codeanalysis:
    runs-on: ubuntu-latest

    steps:
      - name: Main checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Set up pnpm via the official Action (instead of relying on Corepack)
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x  # or pin a specific version

      - name: Get pnpm store directory
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: make install

      - name: Linting
        run: make lint
