name: i18n
on:
  push:
    paths:
      - "*.js"
      - "*.json"
      - "*.yaml"
      - "packages/**"
      - ".github/workflows/i18n.yml"

env:
  NODE_VERSION: 20.x

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Main checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install pnpm directly, bypassing Corepack’s outdated TUF keys.
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          # You can pin a specific version or use a range like '8.x'
          version: 8.x

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: make install

      - name: Test i18n command
        run: make i18n
